version: "3.7"
services:
  shakespokemon:
    image: node:14.5.0-alpine
    volumes:
    - app:/home/shakespokemon:delegated
    working_dir: /home/shakespokemon
    command: npm run start
    ports:
    - 8080:8080
    environment:
      NODE_ENV: development
      SERVER_PORT: 8080

volumes:
  app:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}