version: "3.7"
services:
  shakespokemon:
    image: node:14.5.0-alpine
    volumes:
    - .:/home/shakespokemon
    working_dir: /home/shakespokemon
    command: npm run dev
    ports:
    - 8080:8080
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      RABBITMQ_HOST: rabbitmq